name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 3: Pull Your Docker Image
    - name: Pull Docker Image
      run: docker pull harshinielamvaluthy/harshini-guvi:latest

    # Step 4: SSH into EC2 and Deploy
    - name: SSH and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          echo "Stopping existing container..."
          sudo docker stop harshini-guvi-app || true
          
          echo "Removing old container..."
          sudo docker rm harshini-guvi-app || true
          
          echo "Pulling latest image..."
          sudo docker pull harshinielamvaluthy/harshini-guvi:latest
          
          echo "Starting new container..."
          sudo docker run -d \
            -p 80:80 \
            --restart always \
            --name harshini-guvi-app \
            harshinielamvaluthy/harshini-guvi:latest
          
          echo "Deployment completed successfully!"
